/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterconnectGUI */

#ifndef _Included_InterconnectGUI
#define _Included_InterconnectGUI
#ifdef __cplusplus
extern "C" {
#endif
#undef InterconnectGUI_FOCUS_TRAVERSABLE_UNKNOWN
#define InterconnectGUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef InterconnectGUI_FOCUS_TRAVERSABLE_DEFAULT
#define InterconnectGUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef InterconnectGUI_FOCUS_TRAVERSABLE_SET
#define InterconnectGUI_FOCUS_TRAVERSABLE_SET 2L
#undef InterconnectGUI_TOP_ALIGNMENT
#define InterconnectGUI_TOP_ALIGNMENT 0.0f
#undef InterconnectGUI_CENTER_ALIGNMENT
#define InterconnectGUI_CENTER_ALIGNMENT 0.5f
#undef InterconnectGUI_BOTTOM_ALIGNMENT
#define InterconnectGUI_BOTTOM_ALIGNMENT 1.0f
#undef InterconnectGUI_LEFT_ALIGNMENT
#define InterconnectGUI_LEFT_ALIGNMENT 0.0f
#undef InterconnectGUI_RIGHT_ALIGNMENT
#define InterconnectGUI_RIGHT_ALIGNMENT 1.0f
#undef InterconnectGUI_serialVersionUID
#define InterconnectGUI_serialVersionUID -7644114512714619750LL
#undef InterconnectGUI_serialVersionUID
#define InterconnectGUI_serialVersionUID 4613797578919906343LL
#undef InterconnectGUI_INCLUDE_SELF
#define InterconnectGUI_INCLUDE_SELF 1L
#undef InterconnectGUI_SEARCH_HEAVYWEIGHTS
#define InterconnectGUI_SEARCH_HEAVYWEIGHTS 1L
#undef InterconnectGUI_OPENED
#define InterconnectGUI_OPENED 1L
#undef InterconnectGUI_serialVersionUID
#define InterconnectGUI_serialVersionUID 4497834738069338734LL
#undef InterconnectGUI_DEFAULT_CURSOR
#define InterconnectGUI_DEFAULT_CURSOR 0L
#undef InterconnectGUI_CROSSHAIR_CURSOR
#define InterconnectGUI_CROSSHAIR_CURSOR 1L
#undef InterconnectGUI_TEXT_CURSOR
#define InterconnectGUI_TEXT_CURSOR 2L
#undef InterconnectGUI_WAIT_CURSOR
#define InterconnectGUI_WAIT_CURSOR 3L
#undef InterconnectGUI_SW_RESIZE_CURSOR
#define InterconnectGUI_SW_RESIZE_CURSOR 4L
#undef InterconnectGUI_SE_RESIZE_CURSOR
#define InterconnectGUI_SE_RESIZE_CURSOR 5L
#undef InterconnectGUI_NW_RESIZE_CURSOR
#define InterconnectGUI_NW_RESIZE_CURSOR 6L
#undef InterconnectGUI_NE_RESIZE_CURSOR
#define InterconnectGUI_NE_RESIZE_CURSOR 7L
#undef InterconnectGUI_N_RESIZE_CURSOR
#define InterconnectGUI_N_RESIZE_CURSOR 8L
#undef InterconnectGUI_S_RESIZE_CURSOR
#define InterconnectGUI_S_RESIZE_CURSOR 9L
#undef InterconnectGUI_W_RESIZE_CURSOR
#define InterconnectGUI_W_RESIZE_CURSOR 10L
#undef InterconnectGUI_E_RESIZE_CURSOR
#define InterconnectGUI_E_RESIZE_CURSOR 11L
#undef InterconnectGUI_HAND_CURSOR
#define InterconnectGUI_HAND_CURSOR 12L
#undef InterconnectGUI_MOVE_CURSOR
#define InterconnectGUI_MOVE_CURSOR 13L
#undef InterconnectGUI_NORMAL
#define InterconnectGUI_NORMAL 0L
#undef InterconnectGUI_ICONIFIED
#define InterconnectGUI_ICONIFIED 1L
#undef InterconnectGUI_MAXIMIZED_HORIZ
#define InterconnectGUI_MAXIMIZED_HORIZ 2L
#undef InterconnectGUI_MAXIMIZED_VERT
#define InterconnectGUI_MAXIMIZED_VERT 4L
#undef InterconnectGUI_MAXIMIZED_BOTH
#define InterconnectGUI_MAXIMIZED_BOTH 6L
#undef InterconnectGUI_serialVersionUID
#define InterconnectGUI_serialVersionUID 2673458971256075116LL
/*
 * Class:     InterconnectGUI
 * Method:    nativeInitialize
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_InterconnectGUI_nativeInitialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     InterconnectGUI
 * Method:    nativeRun
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InterconnectGUI_nativeRun
  (JNIEnv *, jobject);

/*
 * Class:     InterconnectGUI
 * Method:    nativeGetLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InterconnectGUI_nativeGetLastError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
