/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Interface_service_NativeInterface */

#ifndef _Included_Interface_service_NativeInterface
#define _Included_Interface_service_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Interface_service_NativeInterface
 * Method:    nativeInitialize
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Interface_service_NativeInterface_nativeInitialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Interface_service_NativeInterface
 * Method:    nativeRun
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Interface_service_NativeInterface_nativeRun
  (JNIEnv *, jobject);

/*
 * Class:     Interface_service_NativeInterface
 * Method:    nativeGetLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Interface_service_NativeInterface_nativeGetLastError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
